version: '3.1'
services:
  redis:
    image: redis
    
  ghost:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8080:2368
    depends_on:
      - redis
      - db
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password:
      database__connection__database: ghost
      url: http://localhost:8080

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True